export const MainPage = {
    headerPreviewTitle: 'Спорт там, где ты!',
    headerTitle1: 'Спорт там, где ты!',
    headerTitle2: 'Инновация <br /> в мире фитнеса.',
    headerTitle3: 'Достигай лучших результатов!',
    headerEnterLink: 'вход в систему',
    headerNavigation1: 'о компании',
    headerNavigation2: 'маркетплейс',
    headerNavigation3: 'новости',
    newsTitle: 'Актуальное',
    newsTitle1: 'Эвалар стал нашим партнером',
    newsDescription1:
        '«SportExpert® Evalar» – выбор чемпионов. Продукция SportExpert® Evalar способствует быстрому восстановлению после физических нагрузок, обеспечению организма энергией, повышению выносливости и эффективности',
    newsTitle2: 'Наш глобальный партнер bop.ru',
    newsDescription2: 'Life style платформа - проверенные поставщики, широкий выбор, гарантия качесва',
    newsTitle3: 'Наши первые клубы партнеры',
    newsDescription3: 'Gym pro, Jump, Capsula, Снегири, Break Olympic, Get fit gym уже в нашей системе',
    newsMoreLink: 'подробнее',
    forClientsTitle: 'The Z.A.L. КЛИЕНТАМ',
    forClientsDescription: 'Мы сделали спорт доступным каждому, <br> создав удобную и функциональную платформу',
    forPartnersTitle: 'The Z.A.L. ПАРТНЕРАМ',
    forPartnersDescription: 'Подключившись к системе, Вы получаете:',
    ecoTitle: 'Welcome to The Z.A.L.',
    ecoDescription:
        'Фитнес-агрегатор с возможностью поминутной оплаты тренировок.<br /><br />Скачивай приложение, выбирай подходящий ZAL, удобное время, занимайся сам или с тренером и оплачивай минуты, потраченные на совершенствование себя.',
    ecoMoreLink: 'подробнее',
    forClientsSlideTitle1: 'ВЫБИРАЙТЕ',
    forClientsSlideTitle2: 'ТРЕНИРУЙТЕСЬ',
    forClientsSlideTitle3: 'ЗАВЕРШАЙТЕ',
    forPartnersSlideTitle1: 'РОСТ ДОХОДОВ',
    forPartnersSlideTitle2: 'АВТОМАТИЗАЦИЮ',
    forPartnersSlideTitle3: 'АНАЛИТИКУ',
    ecoCardTitle1: 'Для клиента',
    ecoCardTitle2: 'Для партнера',
    ecoCardTitle3: 'Для корпоративных клиентов',
    ecoCardTitle4: 'Стать партнером',
    ecoCardTitle5: 'Мероприятия',
    ecoCardTitle6: 'Школа тренеров',
    forClientsSlideDescription1: 'Зал, который подходит по локации, опционалу, стоимости и комфорту',
    forClientsSlideDescription2:
        'Поминутно или приобретайте членство на выгодных условиях, выбирайте формат тренировки и подходящего тренера прямо в приложении',
    forClientsSlideDescription3:
        'Тренировку в один клик, счетчик подскажет в какую сумму обошлась тренировка. Стоимость будет автоматически списана с карты.',
    forPartnersSlideDescription1: 'Дополнительный прирост трафика клиентов за счет рекламной поддержки',
    forPartnersSlideDescription2:
        'Полноценное ПО с CRM-системой, включающую в себя инструментарий со встроенной системой аналитики и отчетностью',
    forPartnersSlideDescription3:
        'Единый аналитический и отчетный центр, маркетинговые и рекламные инструменты, помогающие узнать:<br>- Охват за определенный промежуток времени<br>- Стоимость клика<br>- Коэффициент конверсии в регистрацию/продажу и ROI каждого рекламного объявления<br>- Эффективность работы рекламных источников по отдельности и в совокупности',
    ecoCardDescription1: 'Для тех, кто ценит не только свое время, но и деньги.',
    ecoCardDescription2: 'Все спортивные бренды в одном месте по лучшим ценам.',
    ecoCardDescription3: 'Специальные условия для бизнеса.',
    ecoCardDescription4: 'Программное обеспечение нового поколения.',
    ecoCardDescription5: 'Организация любых спортивных мероприятий под ключ.',
    ecoCardDescription6: 'Обучение тренеров, выдача сертификатов.',
    footerAbout: 'О нас',
    footerHelp: 'Помощь',
    footerComparing: 'Сотрудничество',
    footerDownloadApp: 'Скачать приложение',
    footerFindClub: 'Найти клуб',
    footerTeam: 'Команда',
    footerJob: 'Вакансии',
    footerUserAgreement: 'Пользовательское соглашение',
    footerConfidential: 'Политика конфиденциальности',
    footerClubsRules: 'Правила посещения клубов',
    footerFaq: 'FAQ',
    footerPartners: 'Наши партнеры',
    footerJoinPartner: 'Стать партнером',
    footerCallBack: 'Контакты',
    footerLogo: 'THE Z.A.L. from bop.ru',
    footerCopyright: '©Все права защищены, 2020',
};
